# Generated by Django 5.1.1 on 2024-10-07 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=10)),
                ('occupied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_num', models.CharField(max_length=15)),
                ('patient_relative_name', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_relative_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(max_length=255)),
                ('symptoms', models.TextField()),
                ('prior_ailments', models.TextField(blank=True, null=True)),
                ('dob', models.DateField()),
                ('status', models.CharField(choices=[('Admitted', 'Admitted'), ('Recovered', 'Recovered'), ('Deceased', 'Deceased')], default='Admitted', max_length=10)),
                ('doctors_visiting_time', models.TimeField(blank=True, null=True)),
                ('doctors_notes', models.TextField(blank=True, null=True)),
                ('bed_num', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostpital_management.bed')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostpital_management.doctor')),
            ],
        ),
    ]
